import {StyleSheet} from 'react-native';
import Colors from '../../constants/colors';
import {
  FONT_SIZE_MD,
  FONT_SIZE_SM,
  FONT_SIZE_XL,
  FONT_SIZE_XS,
  POPPINS_BOLD,
  POPPINS_MEDIUM,
  POPPINS_REGULAR,
  POPPINS_SEMIBOLD,
  SCREEN_HEIGHT,
  SCREEN_WIDTH,
  STANDARD_BORDER_RADIUS,
  STANDARD_BUTTON_HEIGHT,
  STANDARD_DRAWER_MENU_ICON_WRAPPER_SIZE,
  STANDARD_FLEX,
  STANDARD_SPACING,
  STANDARD_USER_AVATAR_WRAPPER_SIZE,
  STANDARD_VECTOR_ICON_SIZE,
} from '../../constants/constants';
import {scale} from 'react-native-size-matters';
import colors from '../../constants/colors';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.white,
  },
  headercontainer: {
    backgroundColor: '#1976D280',
    // height: 'auto',
    borderBottomLeftRadius: STANDARD_BORDER_RADIUS * 5,
    borderBottomRightRadius: STANDARD_BORDER_RADIUS * 5,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginHorizontal: STANDARD_SPACING * 2,
    marginTop: STANDARD_SPACING * 3,
  },
  headerview: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  usernamewrapper: {
    // top: scale(2),
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginHorizontal: STANDARD_SPACING * 2,
    marginBottom: scale(10),
  },
  usernamecontainer: {
    right: scale(28),
    top: 5,

    marginRight: scale(22),
  },
  clanderwrapper: {
    backgroundColor: '#1976D2',
    height: scale(30),
    width: scale(94),
    justifyContent: 'space-evenly',
    borderRadius: STANDARD_BORDER_RADIUS * 3,
    flexDirection: 'row',
    padding: scale(5),
    top: scale(26),
  },
  datetxt: {
    fontSize: scale(8),
    fontWeight: '700',
    fontFamily: POPPINS_REGULAR,
    color: Colors.white,
    textAlignVertical: 'center',
  },
  chartview: {
    backgroundColor: '#1976D2',
    height: SCREEN_HEIGHT * 0.25,
    // marginHorizontal: scale(2),
    justifyContent: 'center',
  },
  titleName: {
    fontFamily: POPPINS_MEDIUM,
    fontWeight: '500',
    color: Colors.black,
    textTransform: 'capitalize',
    width: scale(210),
    // marginRight: scale(33),
  },
  drawerMenuIconWrapper: {
    width: STANDARD_DRAWER_MENU_ICON_WRAPPER_SIZE,
    aspectRatio: 1,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: STANDARD_DRAWER_MENU_ICON_WRAPPER_SIZE * 0.5,
    marginBottom: scale(5),
  },
  welcomeLabel: {
    fontFamily: POPPINS_REGULAR,
    fontSize: FONT_SIZE_MD,
    fontWeight: '400',
    left: scale(10),
    // alignSelf:'flex-start',
    textAlignVertical: 'center',
  },
  avatarWrapper: {
    // width: STANDARD_USER_AVATAR_WRAPPER_SIZE,
    aspectRatio: 1,
    borderRadius: STANDARD_USER_AVATAR_WRAPPER_SIZE * 0.5,
    alignItems: 'center',
    justifyContent: 'flex-end',
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: colors.gray,
    // backgroundColor:'red'
    marginBottom: scale(5),
  },
  avatarImage: {
    width: scale(40),
    height: scale(40),
    borderRadius: scale(20),
    resizeMode: 'contain',
  },
  TextWrapper: {
    fontSize: scale(20),
    fontFamily: POPPINS_MEDIUM,
    fontWeight: '500',
    color: Colors.black,
  },
  chartWrapper: {
    // marginVertical:scale(10)
    padding: scale(10),
  },
  totalInvoice: {
    position: 'absolute',
    justifyContent: 'center',
    alignSelf: 'center',
    top: scale(55),
    fontSize: scale(16),
    fontFamily: POPPINS_MEDIUM,
    fontWeight: '700',
    color: Colors.white,
  },
  totalInvoiceText: {
    position: 'absolute',
    justifyContent: 'center',
    alignSelf: 'center',
    top: scale(80),
    fontSize: scale(10),
    fontFamily: POPPINS_REGULAR,
    fontWeight: '700',
    color: Colors.white,
  },
  chartContainer: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-around',
  },
  legendContainer: {
    marginLeft: scale(20),
    width: '40%',
    alignItems: 'center',
    // backgroundColor: 'red',
    alignItems: 'flex-start',
  },
  legendItem: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: scale(10),
  },
  legendColor: {
    width: scale(8),
    height: scale(8),
    borderRadius: scale(4),
    marginRight: scale(10),
    alignSelf: 'center',
    alignItems: 'flex-start',
  },
  legendLabel: {
    fontSize: scale(12),
    fontFamily: POPPINS_MEDIUM,
    fontWeight: '700',
    color: Colors.white,
    // left:4,
    // textAlign:'',
  },
  legendText: {
    fontSize: scale(10),
    fontFamily: POPPINS_REGULAR,
    fontWeight: '700',
    color: Colors.white,
    top: scale(5),
  },
  boxWrapper: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    // backgroundColor:'red',
    paddingHorizontal: scale(12),
  },
  innnerbox: {
    width: SCREEN_WIDTH * 0.45,
    height: SCREEN_HEIGHT * 0.16,
    borderRadius: STANDARD_BORDER_RADIUS * 2,
    borderWidth: scale(1),
    borderColor: colors.gray,
    // backgroundColor: '#7C7C7C4D',
  },
  innerboxview: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: scale(10),
    marginVertical: scale(6),
  },
  ineerboxstyle: {
    width: scale(30),
    height: scale(30),
    borderRadius: scale(15),
    borderWidth: scale(3),
    borderColor: '#0000001A',
  },
  boxtexttitle: {
    fontSize: scale(12),
    fontFamily: POPPINS_REGULAR,
    fontWeight: '700',
    color: Colors.black,
  },
  firstview: {
    alignItems: 'center',
    flexDirection: 'column',
    justifyContent: 'space-around',
    height: scale(60),
  },
  firstviewtxt: {
    fontSize: scale(18),
    fontFamily: POPPINS_BOLD,
    color: Colors.primary,
    fontWeight: '700',
    lineHeight: scale(20),
  },
  firstviewtxts: {
    fontSize: scale(14),
    fontFamily: POPPINS_BOLD,
    color: '#4CAF50',
    fontWeight: '700',
    lineHeight: scale(20),
  },
  Debittxt: {
    fontSize: scale(10),
    fontFamily: POPPINS_REGULAR,
    textAlign: 'center',
    fontWeight: '400',
    color: Colors.black,
  },
  SecondBoxview: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: scale(10),
    marginVertical: scale(6),
    // backgroundColor:'red'
  },
  secondboxstyl: {
    width: scale(25),
    height: scale(25),
    borderRadius: scale(12.5),
    borderWidth: scale(2),
    borderColor: '#0000001A',
  },
  arowicon: {
    top: scale(2),
  },
  boxview: {
    alignItems: 'center',
    flexDirection: 'column',
    justifyContent: 'space-between',
    height: scale(65),
  },
  boxviewtxt: {
    fontSize: scale(18),
    fontFamily: POPPINS_BOLD,
    color: Colors.primary,
    fontWeight: '700',
    // lineHeight: scale(20),
  },
  boxviewwapper: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    width: scale(115),
  },
  invoicewrapper: {
    // padding: scale(10),
    // marginHorizontal: scale(10),
    // marginBottom:scale(10),
  },
  TableWrapper: {
    padding: scale(10),
    // marginVertical: scale(10),
    borderWidth: scale(0.8),
    borderColor: Colors.dividerColor,
    borderRadius: STANDARD_BORDER_RADIUS,
    paddingHorizontal: scale(10),
    // marginBottom:50
    // backgroundColor:'red'
  },
  Table_Tittle: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    // backgroundColor:'red',
    marginVertical: scale(5),
    padding: scale(2),
  },
  Table_Container: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    // backgroundColor:'green',
    marginVertical: scale(5),
    // width:scale(310),
    // padding: scale(5),
  },
  Table_styles: {
    flexDirection: 'column',
    justifyContent: 'space-around',
    // backgroundColor:'pink',
    height: scale(40),
  },
  Table_Bold_Text: {
    fontSize: FONT_SIZE_XS,
    fontFamily: POPPINS_SEMIBOLD,
    fontWeight: '700',
    color: Colors.darkblack,
  },
  Table_Normal_Text: {
    fontSize: FONT_SIZE_XS,
    fontFamily: POPPINS_REGULAR,
    fontWeight: '400',
    color: Colors.black,
  },
  TableDivider: {
    borderBottomWidth: scale(1),
    borderBottomColor: '#7C7C7C',
    width: 'auto',
  },
  containeraaa: {
    // backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center', // Use 'center' to center the rows
    // paddingTop: 40,
  },
  row: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    // backgroundColor:'red',
    width: SCREEN_WIDTH * 0.4,
    // width:'100%',
  },
  box: {
    width: 60,
    height: 60,
    // backgroundColor: 'aqua',
    margin: 2,
  },
  TableStatus: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    right: scale(5),
    alignSelf: 'center',
  },
  bagestyle: {
    backgroundColor: colors.green,
    alignSelf: 'center',
  },
  ButtonContainer: {
    flexDirection: 'row',
    width: SCREEN_WIDTH * 0.45,
    backgroundColor: colors.primary,
    borderRadius: STANDARD_BORDER_RADIUS * 5,
    alignSelf: 'flex-end',
    marginRight: scale(15),
    alignItems: 'center',
    position: 'absolute',
    bottom: scale(10),
  },
  iconbtn: {
    alignItems: 'center',
    marginRight: scale(4),
    bottom: scale(2),
  },
  buttonstyl: {
    flexDirection: 'row',
    borderRadius: STANDARD_BUTTON_HEIGHT * 0.5,
    marginLeft: scale(15),
    width: SCREEN_WIDTH * 0.45,
    alignSelf: 'center',
    alignItems: 'center',
    justifyContent: 'center',
    position: 'absolute',
    bottom: scale(10),
    right: scale(15),
    padding: scale(12),
    backgroundColor: colors.primary,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.2,
    shadowRadius: 1.41,

    elevation: 2,
  },
  labelstyl: {
    fontSize: scale(12),
    fontWeight: '400',
    fontFamily: POPPINS_MEDIUM,
    color: colors.white,
  },
  sectionTitleAndLinkWrapper: {
    margin: STANDARD_SPACING * 2,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  sectionTitle: {
    fontFamily: POPPINS_SEMIBOLD,
    fontSize: FONT_SIZE_MD,
    fontWeight: '500',
  },
});
